# Docker Compose configuration for Airflow and dbt pipeline
services:
  airflow:
    build: .
    environment:
      AIRFLOW__CORE_EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE_SQLALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE_LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE_FERNET_KEY: ''
      AIRFLOW__WEBSERVER_EXPOSE_CONFIG: 'True'
      AIRFLOW__CORE_DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./include:/opt/airflow/include
      - ./expectations:/opt/airflow/expectations
      - ./data:/opt/airflow/data
      - ./transform_project:/opt/airflow/transform_project
    ports:
      - "8081:8080"
    command: bash -c "airflow db migrate && airflow scheduler & airflow webserver"
    restart: always